// pulled on sat 20 june 3AM

export default [
	{
		id: 7320,
		name: 'Sports Center',
		synonyms: ['Gym', 'Indoors Sports', 'Sports Centre'],
	},
	{
		id: 7374,
		name: 'Stadium',
		synonyms: ['Arena', 'Gymnasium', 'Sports Ground', 'Sports Stadium'],
	},
	{
		id: 7315,
		name: 'Restaurant',
		synonyms: ['Dining', 'Eatery', 'Eating House', 'Eating Place'],
	},
	{
		id: 9376,
		name: 'Café/Pub',
		synonyms: ['Ale House', 'Public House', 'Tavern'],
	},
	{
		id: 9663,
		name: 'Health Care Service',
		synonyms: [],
	},
	{
		id: 7321,
		name: 'Hospital',
		synonyms: [
			'Clinic',
			'Hospice',
			'Hospital/Polyclinic',
			'Infirmary',
			'Medical Centre',
			'Polyclinic',
			'Primary Care Centre',
		],
	},
	{
		id: 9373,
		name: 'Doctor',
		synonyms: [
			'Doc',
			"Doctor's Office",
			'Dr',
			'Dr.',
			'MD',
			'Medic',
			'Medical Office',
			'Medical Practitioner',
			'Surgeon',
			'Surgery',
		],
	},
	{
		id: 9361,
		name: 'Shop',
		synonyms: ['Retailer', 'Store'],
	},
	{
		id: 7332,
		name: 'Market',
		synonyms: [],
	},
	{
		id: 9932,
		name: 'Public Amenity',
		synonyms: [],
	},
	{
		id: 7301,
		name: 'Road Traffic Control Center',
		synonyms: ['Traffic Service Center', 'Traffic Service Centre'],
	},
	{
		id: 7324,
		name: 'Post Office',
		synonyms: ['Post', 'Postal Service'],
	},
	{
		id: 7377,
		name: 'College/University',
		synonyms: ['College', 'Tertiary Education', 'Uni', 'University'],
	},
	{
		id: 7369,
		name: 'Open Parking Area',
		synonyms: [
			'Car Park',
			'General Parking',
			'Open Parking',
			'Outdoor Lot',
			'Outdoor Parking',
			'Parking Area',
			'Parking Lot',
			'Parking Place',
			'Public Parking',
		],
	},
	{
		id: 9937,
		name: 'Club & Association',
		synonyms: ['Association', 'Club'],
	},
	{
		id: 7360,
		name: 'Campground',
		synonyms: [
			'Camp Ground',
			'Camp Site',
			'Camping',
			'Camping Area',
			'Camping Ground',
			'Camping Site',
			'Campsite',
			'Holiday Park',
		],
	},
	{
		id: 7304,
		name: 'Vacation Rental',
		synonyms: ['Holiday Rental'],
	},
	{
		id: 9902,
		name: 'Amusement Park',
		synonyms: [],
	},
	{
		id: 7303,
		name: 'Residential Accommodations',
		synonyms: [
			'Apartments',
			'Homes',
			'Houses',
			'Residences',
			'Residential Accommodation',
			'Residential Complex',
		],
	},
	{
		id: 7335,
		name: 'Agricultural Business',
		synonyms: ['Agriculture', 'Agriculture Business', 'Animal Husbandry', 'Husbandry'],
	},
	{
		id: 7383,
		name: 'Airport',
		synonyms: ['Aerodrome'],
	},
	{
		id: 9352,
		name: 'Company',
		synonyms: [
			'Corporation',
			'Employment',
			'Enterprise',
			'Establishment',
			'Firm',
			'Institution',
			'Organisation',
			'Organization',
			'Work',
		],
	},
	{
		id: 9379,
		name: 'Nightlife',
		childCategoryIds: [9379004, 9379006, 9379009, 9379002, 9379008, 9379010, 9379003, 9379007],
		synonyms: [],
	},
	{
		id: 7310,
		name: 'Repair Shop',
		childCategoryIds: [7310002, 7310003, 7310004, 7310008, 7310005, 7310006, 7310009, 7310007],
		synonyms: [
			'Accident Repair',
			'Car Mechanic',
			'Car Repair',
			'Car Servicing',
			'Car Workshop',
			'Crash Repair',
			'Garage',
			'Local Garage',
			'MOT',
			'Mechanic',
			'Mechanic Shop',
			'Panel Beaters',
			'Panelbeaters',
			'Repair Facility',
			'Service Centre',
			'Service Department',
			'Servicing',
			'Vehicle Repair',
			'WOF',
			'Workshop',
		],
	},
	{
		id: 7314,
		name: 'Hotel/Motel',
		childCategoryIds: [7314002, 7314007, 7314004, 7314003, 7314006, 7314005, 7314008],
		synonyms: ['Lodging & Boarding'],
	},
	{
		id: 7372,
		name: 'School',
		synonyms: ['Educational Institution'],
	},
	{
		id: 9910,
		name: 'Automotive Dealer',
		synonyms: [
			'Auto Dealer',
			'Bike Showroom',
			'Car Showroom',
			'Dealer',
			'Dealership',
			'Vehicle Sales',
		],
	},
	{
		id: 9927,
		name: 'Zoo, Arboretum & Botanical Garden',
		synonyms: ['Animal Park'],
	},
	{
		id: 7342,
		name: 'Movie Theater',
		synonyms: [
			'Big Screen',
			'Cinema',
			'Cinema Hall',
			'Film House',
			'Megaplex',
			'Movie',
			'Movie Hall',
			'Movie House',
			'Movie Theatre',
			'Movies',
			'Multi-screen',
			'Multiplex',
			'Picture House',
			'Picture Theater',
			'Picture Theatre',
			'Silver Screen',
			'The Movies',
			'The Pictures',
		],
	},
	{
		id: 7318,
		name: 'Theater',
		synonyms: ['Play House', 'Playhouse', 'Theatre'],
	},
	{
		id: 9362,
		name: 'Park & Recreation Area',
		synonyms: ['Park and Recreation Area'],
	},
	{
		id: 7339,
		name: 'Place of Worship',
		synonyms: ['House of God', 'House of Prayer', 'House of Worship', 'Prayer Hall', 'Shrine'],
	},
	{
		id: 7376,
		name: 'Tourist Attraction',
		synonyms: [
			'Important Tourist Attraction',
			'Landmark',
			'Local Attraction',
			'Place of Interest',
			'Sight Seeing Place',
			'Tourist Place',
		],
	},
	{
		id: 7302,
		name: 'Trails',
		synonyms: ['Nature Trail', 'Trail Network', 'Trail System'],
	},
	{
		id: 7380,
		name: 'Railroad Station',
		synonyms: [
			'Central Station',
			'Rail Station',
			'Rail Yard',
			'Railroad Terminal',
			'Railway Station',
			'Railway Terminal',
			'Railway Terminus',
			'Station',
			'Train Station',
			'Train Stop',
		],
	},
	{
		id: 9942,
		name: 'Public Transportation Stop',
		childCategoryIds: [9942002, 9942005, 9942003, 9942004],
		synonyms: [
			'Public Transit',
			'Public Transit Stop',
			'Public Transport',
			'Public Transport Station',
			'Public Transport Stop',
			'Public Transport Terminus',
			'Terminus',
			'Transit Station',
		],
	},
	{
		id: 9160,
		name: 'Exchange',
		childCategoryIds: [9160003, 9160002],
		synonyms: [],
	},
	{
		id: 7347,
		name: 'Marina',
		childCategoryIds: [7347002, 7347003],
		synonyms: ['Boat Basin', 'Dock', 'Yachting'],
	},
	{
		id: 7359,
		name: 'Weigh Station',
		childCategoryIds: [7359003],
		synonyms: ['Weigh Scales'],
	},
	{
		id: 9155,
		name: 'Car Wash',
		childCategoryIds: [9155003],
		synonyms: ['Auto Detailing', 'Auto Wash', 'Carwash', 'Valet'],
	},
	{
		id: 9378,
		name: 'Leisure Center',
		childCategoryIds: [9378002, 9378003, 9378004, 9378005, 9378006],
		synonyms: ['Leisure Centre', 'Leisure Facilities'],
	},
	{
		id: 7389,
		name: 'Access Gateway',
		childCategoryIds: [7389002, 7389004, 7389003],
		synonyms: [],
	},
	{
		id: 8099,
		name: 'Geographic Feature',
		synonyms: [],
	},
	{
		id: 7380004,
		name: 'Urban Station',
		synonyms: ['Suburban Station'],
	},
	{
		id: 7302003,
		name: 'Adventure Vehicle Trail',
		synonyms: ['Off Road Track'],
	},
	{
		id: 9352003,
		name: 'Advertising Company',
		synonyms: [
			'Ad Agency',
			'Advert Agency',
			'Advertising Agency',
			'Marketing',
			'Marketing Company',
		],
	},
	{
		id: 7315081,
		name: 'Afghan Restaurant',
		synonyms: ['Afghan Cuisine', 'Afghan Food'],
	},
	{
		id: 7315002,
		name: 'African Restaurant',
		synonyms: ['African Cuisine', 'African Food'],
	},
	{
		id: 9361073,
		name: 'Agricultural Supplies',
		synonyms: ['Farm Supplies', 'Farming Supplies'],
	},
	{
		id: 9352012,
		name: 'Agricultural Technology',
		synonyms: [
			'Agriculture',
			'Agriculture Equipment',
			'Farming Equipment',
			'Farming Technology',
		],
	},
	{
		id: 7383005,
		name: 'Airfield',
		synonyms: ['Aerodrome'],
	},
	{
		id: 9352034,
		name: 'Airline Company',
		synonyms: ['Airline'],
	},
	{
		id: 7389002,
		name: 'Airline Access',
		synonyms: ['Airport Terminal', 'Terminal'],
	},
	{
		id: 7315082,
		name: 'Algerian Restaurant',
		synonyms: ['Algerian Cuisine', 'Algerian Food'],
	},
	{
		id: 9663005,
		name: 'Ambulance Unit',
		synonyms: [],
	},
	{
		id: 7315003,
		name: 'American Restaurant',
		synonyms: ['American Cuisine', 'American Food'],
	},
	{
		id: 7318007,
		name: 'Amphitheater',
		synonyms: ['Amphitheatre'],
	},
	{
		id: 9902002,
		name: 'Amusement Arcade',
		synonyms: ['Cyber Café', 'Video Arcade', 'Video Games', 'Video Games Parlour'],
	},
	{
		id: 9902003,
		name: 'Amusement Park',
		synonyms: [],
	},
	{
		id: 9902004,
		name: 'Amusement Place',
		synonyms: [],
	},
	{
		id: 9361048,
		name: 'Animal Services',
		synonyms: [],
	},
	{
		id: 9352045,
		name: 'Animal Shelter',
		synonyms: ['Animal Rescue', 'Animal Sanctuary'],
	},
	{
		id: 9361049,
		name: 'Antique/Art Shop',
		synonyms: [],
	},
	{
		id: 7304006,
		name: 'Apartment Rental',
		synonyms: [],
	},
	{
		id: 9927004,
		name: 'Aquatic Zoo',
		synonyms: ['Aquarium', 'Marine Park'],
	},
	{
		id: 7315083,
		name: 'Arabian Restaurant',
		synonyms: [
			'Arab Cuisine',
			'Arab Food',
			'Arab Restaurant',
			'Arabian Cuisine',
			'Arabian Food',
		],
	},
	{
		id: 9927002,
		name: 'Arboreta & Botanical Gardens',
		synonyms: [
			'Arboreta',
			'Arboretum',
			'Botanical Garden',
			'Botanical Gardens',
			'Garden',
			'Public Garden',
		],
	},
	{
		id: 7376012,
		name: 'Arch',
		synonyms: [],
	},
	{
		id: 7315084,
		name: 'Argentinian Restaurant',
		synonyms: [
			'Argentine Cuisine',
			'Argentine Food',
			'Argentine Restaurant',
			'Argentinian Cuisine',
			'Argentinian Food',
		],
	},
	{
		id: 7315085,
		name: 'Armenian Restaurant',
		synonyms: ['Armenian Cuisine', 'Armenian Food'],
	},
	{
		id: 7372012,
		name: 'Art School',
		synonyms: [],
	},
	{
		id: 7339007,
		name: 'Ashram',
		synonyms: [],
	},
	{
		id: 7315062,
		name: 'Asian Restaurant',
		synonyms: ['Asian Cuisine', 'Asian Food'],
	},
	{
		id: 7374002,
		name: 'Athletics Track',
		synonyms: [
			'Athletic Stadium',
			'Athletics',
			'Athletics Ground',
			'Indoor Athletics Track',
			'Running Track',
		],
	},
	{
		id: 9910009,
		name: 'ATV Dealer',
		synonyms: [
			'ATV Sales',
			'All-Terrain Vehicle Dealer',
			'All-Terrain Vehicle Sales',
			'Quad Bike Dealer',
			'Quad Bike Sales',
			'Snowmobile Dealer',
		],
	},
	{
		id: 7315086,
		name: 'Australian Restaurant',
		synonyms: ['Australian Cuisine', 'Australian Food'],
	},
	{
		id: 7315004,
		name: 'Austrian Restaurant',
		synonyms: ['Austrian Cuisine', 'Austrian Food'],
	},
	{
		id: 9352013,
		name: 'Automobile Company',
		synonyms: [
			'Automobile Factory',
			'Car Company',
			'Car Distribution Center',
			'Car Distribution Centre',
			'Motor Car Company',
		],
	},
	{
		id: 9352041,
		name: 'Automobile Manufacturing',
		synonyms: [
			'Automobile Factory',
			'Automobile Manufacturer',
			'Automotive Manufacturer',
			'Car Factory',
			'Car Manufacturer',
			'Motor Car Manufacturer',
		],
	},
	{
		id: 9361058,
		name: 'Bags & Leatherwear',
		synonyms: ['Bags', 'Leather', 'Leather Goods', 'Leatherwear', 'Purses'],
	},
	{
		id: 7315146,
		name: 'Banquet Rooms',
		synonyms: [
			'Banquet Hall',
			'Banquet Restaurant',
			'Banqueting Room',
			'Function Hall',
			'Function Room',
		],
	},
	{
		id: 9379004,
		name: 'Bar',
		synonyms: ['Ale House'],
	},
	{
		id: 7315005,
		name: 'Barbecue Restaurant',
		synonyms: ['BBQ', 'BBQ Restaurant', 'Barbecue', 'Barbecue Cuisine', 'Barbecue Food'],
	},
	{
		id: 7374009,
		name: 'Baseball Park',
		synonyms: ['Ball Park', 'Ballpark', 'Baseball', 'Baseball Field', 'Baseball Stadium'],
	},
	{
		id: 7374012,
		name: 'Basketball Arena',
		synonyms: ['Basketball', 'Basketball Court', 'Basketball Stadium'],
	},
	{
		id: 7315087,
		name: 'Basque Restaurant',
		synonyms: ['Basque Cuisine', 'Basque Food'],
	},
	{
		id: 9362002,
		name: 'Battlefield',
		synonyms: ['Battleground'],
	},
	{
		id: 8099016,
		name: 'Bay',
		synonyms: [],
	},
	{
		id: 9937002,
		name: 'Beach Club',
		synonyms: [],
	},
	{
		id: 9361067,
		name: 'Beauty Salon',
		synonyms: [
			'Beautician',
			'Beauty',
			'Beauty Center',
			'Beauty Centre',
			'Beauty Parlour',
			'Beauty Shop',
			'Make-up',
		],
	},
	{
		id: 9361050,
		name: 'Beauty Supplies',
		synonyms: ['Beauty Shop', 'Beauty Store'],
	},
	{
		id: 7314002,
		name: 'B&B/Guest House',
		synonyms: [
			'B & B',
			'B and B',
			'B&B',
			'Bed & Breakfast',
			'Bed and Breakfast',
			'Guest House',
			'Guesthouse',
			'Inn',
		],
	},
	{
		id: 7315006,
		name: 'Belgian Restaurant',
		synonyms: ['Belgian Cuisine', 'Belgian Food'],
	},
	{
		id: 9361072,
		name: 'Betting Station',
		synonyms: ['Bookie', 'Bookmaker', 'TAB'],
	},
	{
		id: 7315007,
		name: 'Bistro',
		synonyms: ['Brasserie'],
	},
	{
		id: 9663004,
		name: 'Blood Bank',
		synonyms: [],
	},
	{
		id: 9910004,
		name: 'Boat Dealer',
		synonyms: ['Boat Sales'],
	},
	{
		id: 9362032,
		name: 'Boat Launching Ramp',
		synonyms: [],
	},
	{
		id: 9361083,
		name: 'Boating Equipment & Accessories',
		synonyms: ['Boating', 'Boating Accessories', 'Boating Equipment'],
	},
	{
		id: 7310002,
		name: 'Bodyshop',
		synonyms: [
			'Body Shop',
			'Car Body Shop',
			'Car Bodyshop',
			'Paint Shop',
			'Panel Beater',
			'Panelbeaters',
			'Respray Shop',
			'Spray Painter',
		],
	},
	{
		id: 7315088,
		name: 'Bolivian Restaurant',
		synonyms: ['Bolivian Cuisine', 'Bolivian Food'],
	},
	{
		id: 9361002,
		name: 'Book Shop',
		synonyms: ['Book Seller', 'Book Store', 'Stationery'],
	},
	{
		id: 7315089,
		name: 'Bosnian Restaurant',
		synonyms: ['Bosnian Cuisine', 'Bosnian Food'],
	},
	{
		id: 9378002,
		name: 'Bowling Center',
		synonyms: [
			'Bowling',
			'Bowling Alley',
			'Bowling Centre',
			'Ten Pin Bowling',
			'Ten-Pin Bowling',
		],
	},
	{
		id: 7315072,
		name: 'Brazilian Restaurant',
		synonyms: ['Brazilian Cuisine', 'Brazilian Food'],
	},
	{
		id: 7376010,
		name: 'Bridge',
		synonyms: [],
	},
	{
		id: 9352035,
		name: 'Bridge & Tunnel Operations',
		synonyms: ['Bridge Operations', 'Tunnel Operations'],
	},
	{
		id: 7315008,
		name: 'British Restaurant',
		synonyms: ['British Cuisine', 'British Food'],
	},
	{
		id: 7315142,
		name: 'Buffet Restaurant',
		synonyms: ['Buffet'],
	},
	{
		id: 7376002,
		name: 'Building',
		synonyms: [],
	},
	{
		id: 7315090,
		name: 'Bulgarian Restaurant',
		synonyms: ['Bulgarian Cuisine', 'Bulgarian Food'],
	},
	{
		id: 7304004,
		name: 'Bungalow Rental',
		synonyms: ['Batch Rental', 'Crib Rental'],
	},
	{
		id: 7315091,
		name: 'Burmese Restaurant',
		synonyms: ['Burmese Cuisine', 'Burmese Food'],
	},
	{
		id: 9910008,
		name: 'Bus Dealer',
		synonyms: ['Bus Sales', 'Coach Dealer'],
	},
	{
		id: 9352025,
		name: 'Bus Charter Company',
		synonyms: [
			'Bus Charter',
			'Bus Hire',
			'Bus Hire Company',
			'Bus Rental',
			'Bus Rental Company',
		],
	},
	{
		id: 9352027,
		name: 'Bus Lines',
		synonyms: [
			'Bus Route',
			'Bus Services',
			'Bus Timetables',
			'Local Bus Services',
			'Local Buses',
		],
	},
	{
		id: 9942002,
		name: 'Bus Stop',
		synonyms: ['Bus Station', 'Bus Terminal', 'Terminus'],
	},
	{
		id: 9352039,
		name: 'Business Services',
		synonyms: [],
	},
	{
		id: 7318006,
		name: 'Cabaret Theater',
		synonyms: ['Cabaret', 'Cabaret Theatre', 'Dance Bar'],
	},
	{
		id: 7314007,
		name: 'Cabins & Lodges',
		synonyms: ['Cabin', 'Cabins', 'Hut', 'Lodge', 'Lodges'],
	},
	{
		id: 9352040,
		name: 'Cable & Telephone Company',
		synonyms: [
			'Cable Company',
			'Telecommunications Company',
			'Telecoms Company',
			'Telephone Company',
		],
	},
	{
		id: 9376002,
		name: 'Café',
		synonyms: ['Cafe'],
	},
	{
		id: 7315147,
		name: 'Cafeteria',
		synonyms: ['Cafetaria'],
	},
	{
		id: 7315009,
		name: 'Californian Restaurant',
		synonyms: ['Californian Cuisine', 'Californian Food'],
	},
	{
		id: 7315092,
		name: 'Cambodian Restaurant',
		synonyms: ['Cambodian Cuisine', 'Cambodian Food'],
	},
	{
		id: 7315010,
		name: 'Canadian Restaurant',
		synonyms: ['Canadian Cuisine', 'Canadian Food'],
	},
	{
		id: 8099020,
		name: 'Cape',
		synonyms: [],
	},
	{
		id: 9910002,
		name: 'Car Dealer',
		synonyms: ['Car Dealership'],
	},
	{
		id: 7310003,
		name: 'Car Glass Replacement Shop',
		synonyms: [
			'Auto Glass Repair',
			'Auto Glass Replacement',
			'Car Glass Repair',
			'Car Glass Replacement',
			'Window Replacement',
			'Windscreen Repair',
			'Windshield Repair',
		],
	},
	{
		id: 7360003,
		name: 'Caravan Site',
		synonyms: [
			'Camper Van',
			'Caravan Park',
			'Mobile Home Park',
			'Mobile Park',
			'RV Park',
			'Trailer Park',
		],
	},
	{
		id: 7315011,
		name: 'Caribbean Restaurant',
		synonyms: ['Caribbean Cuisine', 'Caribbean Food'],
	},
	{
		id: 9352043,
		name: 'Catering Services',
		synonyms: ['Caterers', 'Catering'],
	},
	{
		id: 8099003,
		name: 'Cave',
		synonyms: ['Cavern'],
	},
	{
		id: 9361003,
		name: 'CDs, DVD & Videos',
		synonyms: [
			'CD Shop',
			'CD Store',
			'CDs',
			'DVD Shop',
			'DVD Store',
			'DVDs',
			'Music Shop',
			'Record Shop',
			'Record Store',
			'Video Centre',
			'Video Shop',
			'Video Store',
			'Videos',
		],
	},
	{
		id: 9361044,
		name: 'Video Rental Shop',
		synonyms: [
			'CD Rental',
			'Video & Game Rental',
			'Video Parlour',
			'Video Rental',
			'Video Rental Store',
			'Video Store',
			'Video and Game Rental',
		],
	},
	{
		id: 9362003,
		name: 'Cemetery',
		synonyms: ['Crematorium'],
	},
	{
		id: 7304005,
		name: 'Chalet Rental',
		synonyms: ['Chalet'],
	},
	{
		id: 9352014,
		name: 'Chemical Company',
		synonyms: ['Chemical Plant', 'Chemical Supplier'],
	},
	{
		id: 7315070,
		name: 'Chicken Restaurant',
		synonyms: [],
	},
	{
		id: 7372003,
		name: 'Child Care Facility',
		synonyms: [
			'Crèche',
			'Day Care',
			'Day Nursery',
			'Daycare',
			'Daycare Center',
			'Kindergarten',
			'Nursery',
			'Nursery School',
			'Play School',
		],
	},
	{
		id: 7315093,
		name: 'Chilean Restaurant',
		synonyms: ['Chilean Cuisine', 'Chilean Food'],
	},
	{
		id: 7315012,
		name: 'Chinese Restaurant',
		synonyms: ['Chinese Cuisine', 'Chinese Food'],
	},
	{
		id: 9361082,
		name: 'Christmas/Holiday Shop',
		synonyms: [
			'Chrismas Store',
			'Christmas Shop',
			'Christmas Store',
			'Christmas/Holiday Store',
			'Christmas/Vacation Store',
			'Holiday Shop',
			'Holiday Store',
			'Vacation Store',
			'Xmas Store',
		],
	},
	{
		id: 7339002,
		name: 'Church',
		synonyms: ['Abbey', 'Cathedral', 'Chapel', 'Monastery', 'Tabernacle'],
	},
	{
		id: 9352029,
		name: 'Cleaning Services',
		synonyms: ['Cleaners'],
	},
	{
		id: 9361004,
		name: "Children's Clothes",
		synonyms: ["Kids' Clothes"],
	},
	{
		id: 9361005,
		name: 'Footwear & Shoe Repairs',
		synonyms: [
			'Cobbler',
			'Footwear',
			'Shoe Maker',
			'Shoe Repair',
			'Shoe Repairs',
			'Shoe Shop',
			'Shoe Store',
			'Shoes',
			'Shoes Shop',
		],
	},
	{
		id: 9361006,
		name: 'Clothing Shop',
		synonyms: [
			'Apparel',
			'Apparel Store',
			'Clothes',
			'Clothes Shop',
			'Clothes Store',
			'Clothing Store',
			'Clothing hop',
		],
	},
	{
		id: 9361007,
		name: "Men's Clothing",
		synonyms: ["Men's Clothes", 'Menswear'],
	},
	{
		id: 9361079,
		name: 'Specialty Clothing Shop',
		synonyms: ['Specialty Clothing Store'],
	},
	{
		id: 9361008,
		name: "Women's Clothing",
		synonyms: ["Women's Clothes", 'Womenswear'],
	},
	{
		id: 9942005,
		name: 'Coach Stop',
		synonyms: ['Coach', 'Coach Station', 'Coach Terminus'],
	},
	{
		id: 9379006,
		name: 'Cocktail Bar',
		synonyms: ['Cocktail', 'Cocktails'],
	},
	{
		id: 9376006,
		name: 'Coffee Shop',
		synonyms: ['Coffee', 'Coffee House', 'Coffeehouse', 'Coffeeshop'],
	},
	{
		id: 7377002,
		name: 'College/University',
		synonyms: ['College', 'Tertiary Education', 'Uni', 'University'],
	},
	{
		id: 7315094,
		name: 'Colombian Restaurant',
		synonyms: ['Colombian Cuisine', 'Colombian Food'],
	},
	{
		id: 9379009,
		name: 'Comedy Club',
		synonyms: ['Comedy', 'Comedy Bar'],
	},
	{
		id: 9352004,
		name: 'Computer & Data Services',
		synonyms: ['Computer Services', 'Data Services', 'IT Services'],
	},
	{
		id: 9352005,
		name: 'Software Company',
		synonyms: ['Software Design', 'Software Engineering'],
	},
	{
		id: 7318002,
		name: 'Concert Hall',
		synonyms: ['Auditorium', 'Music Hall'],
	},
	{
		id: 7303006,
		name: 'Condominium Complex',
		synonyms: ['Condo', 'Condominium', 'Condominium Block'],
	},
	{
		id: 9352032,
		name: 'Construction Company',
		synonyms: [],
	},
	{
		id: 9361042,
		name: 'Construction Material & Equipment',
		synonyms: [
			'Builders Merchant',
			'Building Supplies',
			'Construction Equipment',
			'Construction Material',
			'Construction Supplies',
		],
	},
	{
		id: 9361009,
		name: 'Convenience Store',
		synonyms: ['7-11', 'Corner Shop', 'Corner Store', 'Dairy', 'General Store', 'Superette'],
	},
	{
		id: 7315095,
		name: 'Corsican Restaurant',
		synonyms: ['Corsican Cuisine', 'Corsican Food'],
	},
	{
		id: 7304002,
		name: 'Cottage Rental',
		synonyms: [],
	},
	{
		id: 8099017,
		name: 'Cove',
		synonyms: [],
	},
	{
		id: 7315063,
		name: 'Creole Restaurant',
		synonyms: ['Creole Cuisine', 'Creole Food'],
	},
	{
		id: 7315013,
		name: 'Crêperie',
		synonyms: ['Pancake House'],
	},
	{
		id: 7374003,
		name: 'Cricket Ground',
		synonyms: [
			'Cricket',
			'Cricket Field',
			'Cricket Green',
			'Cricket Oval',
			'Cricket Pitch',
			'Oval',
		],
	},
	{
		id: 7315096,
		name: 'Cuban Restaurant',
		synonyms: ['Cuban Cuisine', 'Cuban Food'],
	},
	{
		id: 7372015,
		name: 'Culinary School',
		synonyms: ['Catering School', 'Hotel Management Institute'],
	},
	{
		id: 7315097,
		name: 'Cypriot Restaurant',
		synonyms: ['Cypriot Cuisine', 'Cypriot Food'],
	},
	{
		id: 7315068,
		name: 'Czech Restaurant',
		synonyms: ['Czech Cuisine', 'Czech Food'],
	},
	{
		id: 7376007,
		name: 'Dam',
		synonyms: [],
	},
	{
		id: 9378003,
		name: 'Dance Studio & School',
		synonyms: ['Dance Academy', 'Dance School', 'Dance Studio'],
	},
	{
		id: 7315098,
		name: 'Danish Restaurant',
		synonyms: ['Danish Cuisine', 'Danish Food'],
	},
	{
		id: 9361060,
		name: 'Delicatessen',
		synonyms: ['Deli', 'Delicacies'],
	},
	{
		id: 7318008,
		name: 'Dinner Theater',
		synonyms: ['Dinner Theatre'],
	},
	{
		id: 9379002,
		name: 'Disco Club',
		synonyms: ['Club', 'Dance Hall', 'Disco', 'Discotheque', 'Nightclub'],
	},
	{
		id: 9352006,
		name: 'Diversified Financials',
		synonyms: [],
	},
	{
		id: 7315099,
		name: 'Dominican Restaurant',
		synonyms: ['Dominican Cuisine', 'Dominican Food'],
	},
	{
		id: 7315057,
		name: 'Dongbei Restaurant',
		synonyms: ['Dongbei Cuisine', 'Dongbei Food'],
	},
	{
		id: 7315079,
		name: 'Doughnut Restaurant',
		synonyms: ['Donut Restaurant', 'Donuts', 'Doughnut Shop', 'Doughnuts'],
	},
	{
		id: 9361076,
		name: 'Drive Through Bottle Shop',
		synonyms: ['Drive Through Liquor Store'],
	},
	{
		id: 7342003,
		name: 'Drive-In Movies',
		synonyms: ['Drive-In', 'Drive-In Cinema', 'Drive-In Theater', 'Drive-in Theatre'],
	},
	{
		id: 7372016,
		name: 'Driving School',
		synonyms: ["Driver's Ed", "Driver's Education", 'Driving Academy', 'Driving Tuition'],
	},
	{
		id: 9361051,
		name: 'Drug Store',
		synonyms: ['Chemist', 'Drugstore'],
	},
	{
		id: 9361010,
		name: 'Dry Cleaner',
		synonyms: ['Dry Cleaning'],
	},
	{
		id: 8099005,
		name: 'Dune',
		synonyms: [],
	},
	{
		id: 7315014,
		name: 'Dutch Restaurant',
		synonyms: ['Dutch Cuisine', 'Dutch Food'],
	},
	{
		id: 7315100,
		name: 'Egyptian Restaurant',
		synonyms: ['Egyptian Cuisine', 'Egyptian Food'],
	},
	{
		id: 9361052,
		name: 'Electrical Appliances Shop',
		synonyms: ['Electrical Appliances Store'],
	},
	{
		id: 9361011,
		name: 'Cameras & Photography',
		synonyms: ['Camera Store', 'Cameras', 'Photography', 'Photography Store'],
	},
	{
		id: 9361012,
		name: 'Computer & Computer Supplies',
		synonyms: ['Computer', 'Computer Shop', 'Computer Store', 'Computer Supplies'],
	},
	{
		id: 9361013,
		name: 'Consumer Electronics',
		synonyms: ['Electronics', 'Electronics Shop', 'Electronics Store'],
	},
	{
		id: 9361014,
		name: 'Office Equipment',
		synonyms: ['Office Stationery', 'Office Supplies', 'Stationary Store'],
	},
	{
		id: 7315101,
		name: 'English Restaurant',
		synonyms: ['English Cuisine', 'English Food'],
	},
	{
		id: 9352038,
		name: 'Equipment Rental',
		synonyms: ['Equipment Hire'],
	},
	{
		id: 7315132,
		name: 'Erotic Restaurant',
		synonyms: [],
	},
	{
		id: 7315102,
		name: 'Ethiopian Restaurant',
		synonyms: ['Ethiopian Cuisine', 'Ethiopian Food'],
	},
	{
		id: 7315133,
		name: 'Exotic Restaurant',
		synonyms: ['Exotic Cuisine', 'Exotic Food'],
	},
	{
		id: 9361016,
		name: 'Factory Outlet',
		synonyms: ['Factory Store', 'Outlet Store'],
	},
	{
		id: 9362017,
		name: 'Fairground',
		synonyms: ['Funfair'],
	},
	{
		id: 7335004,
		name: 'Farm',
		synonyms: ['Farming'],
	},
	{
		id: 7332004,
		name: 'Farmers Market',
		synonyms: ['Street Market', 'Weekly Market'],
	},
	{
		id: 7315015,
		name: 'Fast Food',
		synonyms: ['Drive Through', 'Fast Food Restaurant', 'Fastfood Restaurant'],
	},
	{
		id: 7315016,
		name: 'Philippine Restaurant',
		synonyms: ['Philippine Cuisine', 'Philippine Food'],
	},
	{
		id: 7315104,
		name: 'Finnish Restaurant',
		synonyms: ['Finnish Cuisine', 'Finnish Food'],
	},
	{
		id: 9362016,
		name: 'Fishing & Hunting Area',
		synonyms: ['Fishing Area', 'Hunting Area'],
	},
	{
		id: 7320002,
		name: 'Fitness Club & Center',
		synonyms: [
			'Fitness Center',
			'Fitness Centre',
			'Fitness Club',
			'Fitness Club & Centre',
			'Fitness Programme',
			'Gym',
			'Gymnasium',
			'Health Club',
			'Indoor Sports',
			'Personal Fitness Training',
			'Wellness Club',
		],
	},
	{
		id: 7303003,
		name: 'Flats/Apartment Complex',
		synonyms: [
			'Apartment Block',
			'Apartment Building',
			'Apartment Complex',
			'Block of Flats',
			'Flats Complex',
		],
	},
	{
		id: 9361017,
		name: 'Florists',
		synonyms: ['Florist', 'Flower Shop', 'Flowers'],
	},
	{
		id: 9378004,
		name: 'Flying Club',
		synonyms: [],
	},
	{
		id: 7315134,
		name: 'Fondue Restaurant',
		synonyms: [],
	},
	{
		id: 9361018,
		name: 'Bakery',
		synonyms: ['Baker', "Baker's", 'Bakers', 'Bread'],
	},
	{
		id: 9361019,
		name: 'Butcher',
		synonyms: ['Butchers Shop', 'Meat'],
	},
	{
		id: 9361020,
		name: 'Fishmonger',
		synonyms: ['Fish', 'Fish Market'],
	},
	{
		id: 9361021,
		name: 'Food Market',
		synonyms: [],
	},
	{
		id: 9361022,
		name: 'Greengrocer',
		synonyms: ['Grocer', 'Vegetable Grocery Store'],
	},
	{
		id: 9361023,
		name: 'Grocery Store',
		synonyms: ['Groceries', 'Grocery'],
	},
	{
		id: 9361024,
		name: 'Other Food Shops',
		synonyms: [],
	},
	{
		id: 9361025,
		name: 'Wine & Spirits',
		synonyms: [
			'Alcohol',
			'Bottle Store',
			'Liquor',
			'Liquor Outlet',
			'Liquor Store',
			'Off Licence',
			'Off License',
			'Spirits',
			'Wholesale Liquor',
			'Wholesaler',
			'Wine',
			'Wine Seller',
			'Wine Shop',
		],
	},
	{
		id: 7374010,
		name: 'Football Stadium',
		synonyms: [
			'American Football Stadium',
			'Football',
			'Football Arena',
			'Football Field',
			'Football Ground',
		],
	},
	{
		id: 9362015,
		name: 'Forest Area',
		synonyms: ['Forest', 'Woods'],
	},
	{
		id: 7315017,
		name: 'French Restaurant',
		synonyms: ['French Cuisine', 'French Food'],
	},
	{
		id: 9352036,
		name: 'Funeral Service & Mortuaries',
		synonyms: [
			'Funeral Director',
			'Funeral Home',
			'Funeral Parlor',
			'Funeral Parlour',
			'Funeral Service',
			'Morgue',
			'Mortician',
			'Mortuaries',
			'Mortuary',
			'Undertaker',
		],
	},
	{
		id: 9361054,
		name: 'Furniture/Home Furnishings',
		synonyms: [
			'Fittings',
			'Furnishings',
			'Furniture',
			'Furniture & Fittings',
			'Furniture Showroom',
			'Home Furnishings',
			'House Fittings',
		],
	},
	{
		id: 7315071,
		name: 'Fusion Restaurant',
		synonyms: ['Fusion Cuisine', 'Fusion Food'],
	},
	{
		id: 7324002,
		name: 'Post Office',
		synonyms: ['Post', 'Postal Service'],
	},
	{
		id: 7310004,
		name: 'Car Repair and Service',
		synonyms: ['Car Repair', 'Car Workshop'],
	},
	{
		id: 9373002,
		name: 'General Practitioner',
		synonyms: ['GP', 'MD', 'Medical Practitioner', 'Physician'],
	},
	{
		id: 7315018,
		name: 'German Restaurant',
		synonyms: ['German Cuisine', 'German Food'],
	},
	{
		id: 9361026,
		name: 'Gifts, Cards, Novelties & Souvenirs',
		synonyms: ['Cards', 'Gift Shop', 'Gifts', 'Novelties', 'Souvenir Shop', 'Souvenirs'],
	},
	{
		id: 9361055,
		name: 'Glassware/Ceramic Shop',
		synonyms: [
			'Ceramic Shop',
			'Ceramic Store',
			'Ceramics',
			'Glassware',
			'Glassware Shop',
			'Pottery Shop',
		],
	},
	{
		id: 9160003,
		name: 'Gold Exchange',
		synonyms: [],
	},
	{
		id: 7315019,
		name: 'Greek Restaurant',
		synonyms: ['Greek Cuisine', 'Greek Food'],
	},
	{
		id: 7315020,
		name: 'Grill Restaurant',
		synonyms: ['Grill', 'Grill Cuisine', 'Grill Food', 'Tandoor Shop'],
	},
	{
		id: 7315054,
		name: 'Guangdong Restaurant',
		synonyms: [
			'Cantonese Cuisine',
			'Cantonese Food',
			'Cantonese Restaurant',
			'Guangdong Cuisine',
			'Guangdong Food',
		],
	},
	{
		id: 7339006,
		name: 'Gurudwara',
		synonyms: [],
	},
	{
		id: 9361027,
		name: 'Hairdresser',
		synonyms: ['Hair Saloon', 'Hair Styling', 'Hair Stylist', 'Salon'],
	},
	{
		id: 7315069,
		name: 'Hamburger Restaurant',
		synonyms: ['Burger Joint', 'Burgers', 'Hamburgers'],
	},
	{
		id: 8099018,
		name: 'Harbor',
		synonyms: ['Harbour', 'Haven'],
	},
	{
		id: 9361069,
		name: 'Hardware Store',
		synonyms: ['Hardware Shop', 'Hardware Supplies', 'Household Hardware'],
	},
	{
		id: 7315021,
		name: 'Hawaiian Restaurant',
		synonyms: ['Hawaiian Cuisine', 'Hawaiian Food'],
	},
	{
		id: 7372006,
		name: 'High School',
		synonyms: ['Secondary School'],
	},
	{
		id: 7302004,
		name: 'Hiking Trail',
		synonyms: ['Hiking Path', 'Walking Trail'],
	},
	{
		id: 8099025,
		name: 'Hill',
		synonyms: [],
	},
	{
		id: 9362004,
		name: 'Historic Site',
		synonyms: ['Archeological Site'],
	},
	{
		id: 9362005,
		name: 'Historical Park',
		synonyms: ['Archeological Park'],
	},
	{
		id: 9361053,
		name: 'Hobby Shop',
		synonyms: [
			'Craft Shop',
			'Craft Store',
			'Free Time Shop',
			'Free Time Store',
			'Hobby Store',
			'Hobby/Free Time Shop',
		],
	},
	{
		id: 9937003,
		name: 'Hockey Club',
		synonyms: [],
	},
	{
		id: 9352044,
		name: 'Home Appliance Repair',
		synonyms: [
			'Appliance Repair',
			'Domestic Appliance Repair',
			'Electrical Appliance Repair',
			'Repair Shop',
		],
	},
	{
		id: 7374005,
		name: 'Horse Racing Track',
		synonyms: [
			'Horse Race Track',
			'Horse Racing',
			'Horse Racing Stadium',
			'Race Course',
			'Race Track',
		],
	},
	{
		id: 7320003,
		name: 'Horse Riding Center',
		synonyms: [
			'Equestrian Center',
			'Equestrian Centre',
			'Equestrianism',
			'Horse Riding',
			'Horse Riding Centre',
			'Pony Club',
			'Riding School',
		],
	},
	{
		id: 7335002,
		name: 'Horticulture',
		synonyms: ['Gardener', 'Gardening', 'Nursery'],
	},
	{
		id: 7321005,
		name: 'Hospital for Women and Children',
		synonyms: ["Women's & Children's Hospital"],
	},
	{
		id: 7321004,
		name: 'Hospital of Chinese Medicine',
		synonyms: [],
	},
	{
		id: 7314004,
		name: 'Hostel',
		synonyms: ['Hostelry'],
	},
	{
		id: 7315058,
		name: 'Hot Pot Restaurant',
		synonyms: [],
	},
	{
		id: 7314003,
		name: 'Hotel',
		synonyms: [],
	},
	{
		id: 9361028,
		name: 'Carpet/Floor Coverings',
		synonyms: ['Carpet', 'Carpets', 'Floor Covering', 'Floor Tiles', 'Tiles'],
	},
	{
		id: 9361029,
		name: 'Curtains/Textiles',
		synonyms: ['Curtains', 'Curtains/Textiles Shop', 'Textiles'],
	},
	{
		id: 9361030,
		name: 'Do-It-Yourself Centers',
		synonyms: ['DIY', 'DIY Store', 'Do-It-Yourself', 'Do-It-Yourself Centres'],
	},
	{
		id: 9361031,
		name: 'House & Garden: Furniture & Fittings',
		synonyms: [],
	},
	{
		id: 9361032,
		name: 'Garden Centers & Services',
		synonyms: [
			'Garden Center',
			'Garden Centers',
			'Garden Centre',
			'Garden Centres & Services',
			'Garden Services',
		],
	},
	{
		id: 9361080,
		name: 'Glass & Windows Store',
		synonyms: ['Glass Shop', 'Glass Store', 'Glazier', 'Window Shop', 'Window Store'],
	},
	{
		id: 9361033,
		name: 'Kitchens & Bathrooms',
		synonyms: ['Kitchen Store', 'Kitchens & Sanitory Store', 'Sanitory Accessories'],
	},
	{
		id: 9361034,
		name: 'Lighting Shops',
		synonyms: [
			'Lamps',
			'Light Shop',
			'Lighting',
			'Lighting Store',
			'Lighting Stores',
			'Lights',
		],
	},
	{
		id: 9361035,
		name: 'Painting & Decorating',
		synonyms: [
			'Decorating',
			'Decorator',
			'Interior Designers',
			'Paint',
			'Paint Shop',
			'Painter',
			'Painting',
			'Wallpaper',
		],
	},
	{
		id: 7315052,
		name: 'Hunan Restaurant',
		synonyms: [
			'Hunan Cuisine',
			'Hunan Food',
			'Xiang Cuisine',
			'Xiang Food',
			'Xiang Restaurant',
		],
	},
	{
		id: 7315022,
		name: 'Hungarian Restaurant',
		synonyms: ['Hungarian Cuisine', 'Hungarian Food'],
	},
	{
		id: 7315078,
		name: 'Ice Cream Parlor',
		synonyms: [],
	},
	{
		id: 7374008,
		name: 'Ice Hockey Arena',
		synonyms: ['Ice Hockey', 'Ice Hockey Stadium', 'Ice Rink'],
	},
	{
		id: 9352042,
		name: 'Import/Export and Distribution',
		synonyms: [
			'Distribution',
			'Distribution Company',
			'Export',
			'Export Company',
			'Import',
			'Import Company',
			'Import, Export and Distribution Company',
			'Import/Export',
		],
	},
	{
		id: 7315023,
		name: 'Indian Restaurant',
		synonyms: ['Indian Cuisine', 'Indian Food'],
	},
	{
		id: 7315024,
		name: 'Indonesian Restaurant',
		synonyms: ['Indonesian Cuisine', 'Indonesian Food'],
	},
	{
		id: 7332002,
		name: 'Informal Market',
		synonyms: [],
	},
	{
		id: 9352007,
		name: 'Insurance Company',
		synonyms: ['Insurance', 'Insurance Agency', 'Insurance Agent', 'Insurance Broker'],
	},
	{
		id: 7315073,
		name: 'International Restaurant',
		synonyms: ['International Cuisine', 'International Food'],
	},
	{
		id: 7380002,
		name: 'International Railroad Station',
		synonyms: ['International Railway Station'],
	},
	{
		id: 9376004,
		name: 'Internet Café',
		synonyms: [],
	},
	{
		id: 9352037,
		name: 'Investment Advisor',
		synonyms: ['Financial Advisor'],
	},
	{
		id: 7315105,
		name: 'Iranian Restaurant',
		synonyms: ['Iranian Cuisine', 'Iranian Food'],
	},
	{
		id: 7315065,
		name: 'Irish Restaurant',
		synonyms: ['Irish Cuisine', 'Irish Food'],
	},
	{
		id: 8099022,
		name: 'Island',
		synonyms: [],
	},
	{
		id: 7315106,
		name: 'Israeli Restaurant',
		synonyms: ['Israeli Cuisine', 'Israeli Food'],
	},
	{
		id: 7315025,
		name: 'Italian Restaurant',
		synonyms: ['Italian Cuisine', 'Italian Food'],
	},
	{
		id: 7315066,
		name: 'Jamaican Restaurant',
		synonyms: ['Jamaican Cuisine', 'Jamaican Food'],
	},
	{
		id: 7315026,
		name: 'Japanese Restaurant',
		synonyms: ['Japanese Cuisine', 'Japanese Food'],
	},
	{
		id: 9379008,
		name: 'Jazz Club',
		synonyms: ['Jazz', 'Jazz Bar'],
	},
	{
		id: 9361036,
		name: 'Jewelry, Clocks & Watches',
		synonyms: [
			'Clock Shop',
			'Clockmaker',
			'Clocks',
			'Jewelers',
			'Jeweller',
			'Jewelry',
			'Jewelry Shop',
			'Jewelry Store',
			'Watch Company',
			'Watch Repairs',
			'Watches',
			'Watchmaker',
		],
	},
	{
		id: 7315027,
		name: 'Jewish Restaurant',
		synonyms: ['Jewish Cuisine', 'Jewish Food'],
	},
	{
		id: 7377003,
		name: 'Junior College/Community College',
		synonyms: [
			'Polytech',
			'Polytechnic',
			'Sixth Form College',
			'TAFE College',
			'Technical and Further Education College',
			'University of Technology',
		],
	},
	{
		id: 9379010,
		name: 'Karaoke Club',
		synonyms: ['Karaoke', 'Karaoke Bar', 'Karaoke Nights'],
	},
	{
		id: 7315028,
		name: 'Korean Restaurant',
		synonyms: ['Korean Cuisine', 'Korean Food'],
	},
	{
		id: 7315067,
		name: 'Kosher Restaurant',
		synonyms: ['Kosher Cuisine', 'Kosher Food'],
	},
	{
		id: 8099019,
		name: 'Lagoon',
		synonyms: [],
	},
	{
		id: 9362006,
		name: 'Lakeshore',
		synonyms: ['Lake', 'Lakeside'],
	},
	{
		id: 7372010,
		name: 'Language School',
		synonyms: ['Language Academy'],
	},
	{
		id: 7315029,
		name: 'Latin American Restaurant',
		synonyms: ['Latin American Cuisine', 'Latin American Food'],
	},
	{
		id: 9361045,
		name: 'Laundry',
		synonyms: ['Launderette', 'Laundrette', 'Laundromat', 'Laundry Store'],
	},
	{
		id: 7315030,
		name: 'Lebanese Restaurant',
		synonyms: ['Lebanese Cuisine', 'Lebanese Food'],
	},
	{
		id: 9352023,
		name: 'Legal Services',
		synonyms: [
			'Advocate',
			'Attorney',
			'Barrister',
			'Judicial',
			'Justice',
			'Law',
			'Law Office',
			'Law Service',
			'Lawyer',
			'Legal',
			'Solicitor',
		],
	},
	{
		id: 7324003,
		name: 'Local Post Office',
		synonyms: [],
	},
	{
		id: 9361056,
		name: 'Local Specialities Shop',
		synonyms: ['Farm Shop', 'Handicraft Store', 'Local Produce', 'Local Specialties Shop'],
	},
	{
		id: 8099027,
		name: 'Locale',
		synonyms: [],
	},
	{
		id: 9361071,
		name: 'Lottery Shop',
		synonyms: ['Lottery Store', 'Lotto', 'Lotto Store'],
	},
	{
		id: 7315107,
		name: 'Luxembourgian Restaurant',
		synonyms: ['Luxembourgian Cuisine', 'Luxembourgian Food'],
	},
	{
		id: 7315135,
		name: 'Macrobiotic Restaurant',
		synonyms: ['Macrobiotic Cuisine', 'Macrobiotic Food'],
	},
	{
		id: 7315108,
		name: 'Maghrib Restaurant',
		synonyms: [
			'Maghreb Cuisine',
			'Maghreb Food',
			'Maghreb Restaurant',
			'Maghrib Cuisine',
			'Maghrib Food',
			'Moroccan Restaurant',
		],
	},
	{
		id: 9352008,
		name: 'Delivery Service',
		synonyms: [
			'Courier',
			'Freight',
			'Freight Delivery',
			'Mail Delivery',
			'Package Delivery',
			'Parcel Delivery',
		],
	},
	{
		id: 7315031,
		name: 'Maltese Restaurant',
		synonyms: ['Maltese Cuisine', 'Maltese Food'],
	},
	{
		id: 9352011,
		name: 'Manufacturing Company',
		synonyms: ['Manufacture', 'Manufacturing'],
	},
	{
		id: 7347002,
		name: 'Marina',
		synonyms: ['Boat Basin', 'Dock', 'Yachting'],
	},
	{
		id: 9361065,
		name: 'Marine Electronic Equipment',
		synonyms: [],
	},
	{
		id: 8099023,
		name: 'Marsh',
		synonyms: ['Bog', 'Swamp', 'Wetlands'],
	},
	{
		id: 7315109,
		name: 'Mauritian Restaurant',
		synonyms: ['Mauritian Cuisine', 'Mauritian Food'],
	},
	{
		id: 7376011,
		name: 'Mausoleum/Grave',
		synonyms: ['Grave', 'Mausoleum'],
	},
	{
		id: 9352016,
		name: 'Mechanical Engineering',
		synonyms: [],
	},
	{
		id: 9361043,
		name: 'Medical Supplies & Equipment',
		synonyms: ['Medical Distributor', 'Medical Equipment', 'Medical Supplies'],
	},
	{
		id: 7315032,
		name: 'Mediterranean Restaurant',
		synonyms: ['Mediterranean Cuisine', 'Mediterranean Food'],
	},
	{
		id: 9362007,
		name: 'Memorial',
		synonyms: [],
	},
	{
		id: 7380005,
		name: 'Subway Station',
		synonyms: [
			'Metro',
			'Metro Station',
			'Subway',
			'Tube',
			'Underground',
			'Underground Station',
		],
	},
	{
		id: 7315033,
		name: 'Mexican Restaurant',
		synonyms: ['Mexican Cuisine', 'Mexican Food'],
	},
	{
		id: 9376007,
		name: 'Microbrewery',
		synonyms: ['Beer Garden', 'Independent Brewery'],
	},
	{
		id: 7315034,
		name: 'Middle Eastern Restaurant',
		synonyms: ['Middle Eastern Cuisine', 'Middle Eastern Food'],
	},
	{
		id: 7372014,
		name: 'Middle School',
		synonyms: ['Intermediate School', 'Junior High'],
	},
	{
		id: 7383004,
		name: 'Military Airport',
		synonyms: ['Air Force Base', 'Defence Airport'],
	},
	{
		id: 8099021,
		name: 'Mineral/Hot Springs',
		synonyms: ['Hot Springs', 'Mineral Springs', 'Spring Bath'],
	},
	{
		id: 9352031,
		name: 'Mining Company',
		synonyms: ['Mine', 'Mining'],
	},
	{
		id: 9361075,
		name: 'Mobile Phone Shop',
		synonyms: ['Cell Phone Shop', 'Cell Phone Store', 'Cell Phones', 'Smart Phones'],
	},
	{
		id: 7315110,
		name: 'Mongolian Restaurant',
		synonyms: ['Mongolian Cuisine', 'Mongolian Food'],
	},
	{
		id: 7376003,
		name: 'Monument',
		synonyms: ['Cenotaph'],
	},
	{
		id: 7315074,
		name: 'Moroccan Restaurant',
		synonyms: ['Moroccan Cuisine', 'Moroccan Food'],
	},
	{
		id: 7339003,
		name: 'Mosque',
		synonyms: ['Masjid'],
	},
	{
		id: 7314006,
		name: 'Motel',
		synonyms: [],
	},
	{
		id: 7374011,
		name: 'Motor Racing Stadium',
		synonyms: [
			'Motor Racing',
			'Motor Racing Circuit',
			'Motor Racing Track',
			'Motor Sport',
			'Motorsport',
			'Motorsport Circuit',
		],
	},
	{
		id: 9910003,
		name: 'Motorcycle Dealer',
		synonyms: [
			'Bike Dealer',
			'Motor Cycle Dealer',
			'Motorbike Dealer',
			'Motorbike Sales',
			'Motorcycle Sales',
			'Scooter Dealer',
		],
	},
	{
		id: 7310008,
		name: 'Motorcycle Repair',
		synonyms: ['Motorbike Repair', 'Motorbike Servicing', 'Motorcycle Servicing'],
	},
	{
		id: 7302002,
		name: 'Mountain Bike Trail',
		synonyms: ['Mountain Bike Path'],
	},
	{
		id: 8099002,
		name: 'Mountain Peak',
		synonyms: [
			'Highest Point',
			'Mountain Crest',
			'Mountain Crown',
			'Mountain Summit',
			'Mountain Tip',
			'Mountain Top',
			'Peak',
			'Summit',
		],
	},
	{
		id: 9352033,
		name: 'Moving & Storage Company',
		synonyms: [
			'Cargo Company',
			'Movers',
			'Moving Company',
			'Removals',
			'Removals Company',
			'Self Storage',
			'Storage',
			'Storage Company',
			'Storage Facility',
		],
	},
	{
		id: 7374006,
		name: 'Multi-Purpose Stadium',
		synonyms: [],
	},
	{
		id: 7318003,
		name: 'Music Center',
		synonyms: ['Music Centre'],
	},
	{
		id: 9361059,
		name: 'Music Instruments Store',
		synonyms: [
			'Music Instruments Shop',
			'Music Shop',
			'Music Store',
			'Musical Instruments Shop',
			'Musical Instruments Store',
		],
	},
	{
		id: 7315136,
		name: 'Mussels Restaurant',
		synonyms: ['Mussels'],
	},
	{
		id: 9361068,
		name: 'Nail Salon',
		synonyms: ['Manicure', 'Nail Bar', 'Nails', 'Pedicure'],
	},
	{
		id: 7380003,
		name: 'National Railroad Station',
		synonyms: ['National Railway Station'],
	},
	{
		id: 9362030,
		name: 'Natural Recreation Attraction',
		synonyms: ['Natural Attraction'],
	},
	{
		id: 7315111,
		name: 'Nepalese Restaurant',
		synonyms: ['Nepalese Cuisine', 'Nepalese Food'],
	},
	{
		id: 7374014,
		name: 'Netball Stadium',
		synonyms: ['Netball', 'Netball Arena', 'Netball Court', 'Netball Ground'],
	},
	{
		id: 9361037,
		name: 'Newsagents & Tobacconists',
		synonyms: [
			'Newsagency',
			'Newsagent',
			"Newsagent's Shop",
			'Newsstand',
			'Pan Shop',
			'Paper Mart',
			'Tobacconist',
		],
	},
	{
		id: 7315112,
		name: 'Norwegian Restaurant',
		synonyms: ['Norwegian Cuisine', 'Norwegian Food'],
	},
	{
		id: 8099011,
		name: 'Oasis',
		synonyms: [],
	},
	{
		id: 7376005,
		name: 'Observatory',
		synonyms: [],
	},
	{
		id: 9352021,
		name: 'OEM',
		synonyms: ['Original Equipment Manufacturer'],
	},
	{
		id: 9352030,
		name: 'Oil & Natural Gas',
		synonyms: ['Gas Company', 'Natural Gas', 'Oil', 'Oil & Natural Gas Company', 'Oil Company'],
	},
	{
		id: 7318004,
		name: 'Opera House',
		synonyms: ['Opera'],
	},
	{
		id: 9361038,
		name: 'Optician',
		synonyms: ['Eye Doctor', 'Optometrist'],
	},
	{
		id: 7315075,
		name: 'Organic Food Restaurant',
		synonyms: ['Organic Cuisine', 'Organic Food', 'Organic Restaurant'],
	},
	{
		id: 7315035,
		name: 'Oriental Restaurant',
		synonyms: ['Oriental Cuisine', 'Oriental Food'],
	},
	{
		id: 7310005,
		name: 'Other Repair Shops',
		synonyms: [],
	},
	{
		id: 9362025,
		name: 'Other Winter Sport',
		synonyms: [],
	},
	{
		id: 7339008,
		name: 'Pagoda',
		synonyms: [],
	},
	{
		id: 7315127,
		name: 'Pakistani Restaurant',
		synonyms: ['Pakistani Cuisine', 'Pakistani Food'],
	},
	{
		id: 8099009,
		name: 'Pan',
		synonyms: [],
	},
	{
		id: 9362008,
		name: 'Park',
		synonyms: ['Parkland'],
	},
	{
		id: 9362009,
		name: 'Parkway',
		synonyms: [],
	},
	{
		id: 9932002,
		name: 'Passenger Transport Ticket Office',
		synonyms: ['Ticket Counter', 'Ticket Office'],
	},
	{
		id: 9361070,
		name: 'Pawn Shop',
		synonyms: ['Pawnbroker', 'Pawnshop'],
	},
	{
		id: 9932003,
		name: 'Pedestrian Subway',
		synonyms: ['Subway', 'Underpass'],
	},
	{
		id: 9663003,
		name: 'Personal Care Facility',
		synonyms: [],
	},
	{
		id: 9663002,
		name: 'Personal Service',
		synonyms: [],
	},
	{
		id: 7315061,
		name: 'Peruvian Restaurant',
		synonyms: ['Peruvian Cuisine', 'Peruvian Food'],
	},
	{
		id: 9361064,
		name: 'Pet Supplies',
		synonyms: ['Pet Shop', 'Pet Store'],
	},
	{
		id: 9352018,
		name: 'Pharmaceutical Company',
		synonyms: ['Drug Company'],
	},
	{
		id: 9361046,
		name: 'Photo Lab/Development',
		synonyms: [
			'Minilab',
			'Photo Developers',
			'Photo Developing',
			'Photo Development',
			'Photo Lab',
			'Photo Studio',
		],
	},
	{
		id: 9361047,
		name: 'Photocopy Shop',
		synonyms: [
			'Copiers',
			'Copy Shop',
			'Photocopiers',
			'Photocopying',
			'Photocopying Shop',
			'Xerox Shop',
		],
	},
	{
		id: 9362033,
		name: 'Picnic Area',
		synonyms: ['Picnic Ground'],
	},
	{
		id: 7315036,
		name: 'Pizzeria',
		synonyms: ['Pizza', 'Pizza Parlor', 'Pizza Restaurant', 'Pizza Shop', 'Pizzaria'],
	},
	{
		id: 8099007,
		name: 'Plain/Flat',
		synonyms: ['Flat', 'Plain'],
	},
	{
		id: 7376006,
		name: 'Planetarium',
		synonyms: [],
	},
	{
		id: 8099008,
		name: 'Plateau',
		synonyms: [],
	},
	{
		id: 7315037,
		name: 'Polish Restaurant',
		synonyms: ['Polish Cuisine', 'Polish Food'],
	},
	{
		id: 7315129,
		name: 'Polynesian Restaurant',
		synonyms: ['Polynesian Cuisine', 'Polynesian Food'],
	},
	{
		id: 7315038,
		name: 'Portuguese Restaurant',
		synonyms: ['Portuguese Cuisine', 'Portuguese Food'],
	},
	{
		id: 7372004,
		name: 'Pre School',
		synonyms: ['Kindergarten', 'Nursery School', 'Pre-School', 'Preschool'],
	},
	{
		id: 9362010,
		name: 'Preserve',
		synonyms: [],
	},
	{
		id: 7335003,
		name: 'Primary Producer',
		synonyms: [],
	},
	{
		id: 7372005,
		name: 'Primary School',
		synonyms: ['Elementary School', 'Infant School', 'Junior School'],
	},
	{
		id: 7383003,
		name: 'Private Airport',
		synonyms: [],
	},
	{
		id: 9379003,
		name: 'Private Club',
		synonyms: ["Members' Club"],
	},
	{
		id: 7315130,
		name: 'Provençal Restaurant',
		synonyms: ['Provençal Cuisine', 'Provençal Food'],
	},
	{
		id: 9376003,
		name: 'Pub',
		synonyms: ['Public House'],
	},
	{
		id: 7315039,
		name: 'Pub Food',
		synonyms: ['Bar Food', 'Bar Snacks'],
	},
	{
		id: 7332003,
		name: 'Public Market',
		synonyms: [],
	},
	{
		id: 7383002,
		name: 'Public Airport',
		synonyms: [],
	},
	{
		id: 9932004,
		name: 'Public Call Box',
		synonyms: [
			'Call Box',
			'PCO',
			'Payphone',
			'Phone Booth',
			'Phone Box',
			'Public Phone',
			'Public Telephone Box',
			'Telephone Box',
		],
	},
	{
		id: 9352017,
		name: 'Public Health Technology Company',
		synonyms: ['Public Health Tech Company'],
	},
	{
		id: 9352019,
		name: 'Publishing Technologies',
		synonyms: ['Publishing House'],
	},
	{
		id: 8099026,
		name: 'Quarry',
		synonyms: [],
	},
	{
		id: 7374013,
		name: 'Race Track',
		synonyms: [
			'Racecourse',
			'Races',
			'Racetrack',
			'Raceway',
			'Racing',
			'Racing Circuit',
			'Racing Track',
			'Track',
		],
	},
	{
		id: 7380006,
		name: 'Railroad Siding',
		synonyms: ['Railway Siding'],
	},
	{
		id: 8099015,
		name: 'Rapids',
		synonyms: [],
	},
	{
		id: 9352009,
		name: 'Real Estate Company',
		synonyms: [
			'Commercial Property Agent',
			'Estate Agent',
			'Land Agent',
			'Real Estate',
			'Real Estate Agency',
			'Real Estate Agent',
			'Real Estate Agents',
			'Real Estate Broker',
		],
	},
	{
		id: 9361015,
		name: 'Real Estate Agent',
		synonyms: [
			'Commercial Property Agent',
			'Estate Agent',
			'Land Agent',
			'Real Estate Broker',
			'Realtor',
		],
	},
	{
		id: 9362011,
		name: 'Recreation Area',
		synonyms: ['Recreation'],
	},
	{
		id: 7360002,
		name: 'Recreational Camping Ground',
		synonyms: [],
	},
	{
		id: 9910005,
		name: 'Recreational Vehicle Dealer',
		synonyms: [
			'Camper Van Dealer',
			'Caravan Dealer',
			'Motorhome Dealer',
			'Motorhome Sales',
			'RV Dealer',
			'RV Sales',
			'Recreational Vehicle Sales',
		],
	},
	{
		id: 9361057,
		name: 'Recycling Shop',
		synonyms: ['Charity Shop', 'Second-hand Shop', 'Thrift Store'],
	},
	{
		id: 8099014,
		name: 'Reef',
		synonyms: [],
	},
	{
		id: 8099013,
		name: 'Reservoir',
		synonyms: [],
	},
	{
		id: 7303004,
		name: 'Residential Estate',
		synonyms: ['Housing Estate', 'Housing Project', 'Residential Colony'],
	},
	{
		id: 7314005,
		name: 'Resort',
		synonyms: [],
	},
	{
		id: 7314008,
		name: 'Rest Camp',
		synonyms: [],
	},
	{
		id: 9361063,
		name: 'Retail Outlet',
		synonyms: [],
	},
	{
		id: 7303002,
		name: 'Retirement Community',
		synonyms: ['Nursing Home', 'Old Age Home', 'Retirement Home', 'Retirement Village'],
	},
	{
		id: 8099004,
		name: 'Ridge',
		synonyms: [],
	},
	{
		id: 8099024,
		name: 'River Crossing',
		synonyms: ['Ford'],
	},
	{
		id: 9932006,
		name: 'Road Rescue',
		synonyms: [
			'AAA',
			'Breakdown Assistance',
			'Breakdown Rescue',
			'Breakdown Service',
			'Road Assistance',
			'Roadside Assistance',
			'Tow Truck',
			'Vehicle Assistance',
		],
	},
	{
		id: 7315041,
		name: 'Roadside Restaurant',
		synonyms: ['Diner', 'Food Joint', 'Road House', 'Roadhouse'],
	},
	{
		id: 7302006,
		name: 'Rock Climbing Trail',
		synonyms: ['Rock Climbing Route'],
	},
	{
		id: 8099012,
		name: 'Rocks',
		synonyms: [],
	},
	{
		id: 7374007,
		name: 'Rugby Ground',
		synonyms: ['Rugby', 'Rugby Pitch', 'Rugby Stadium'],
	},
	{
		id: 7315131,
		name: 'Romanian Restaurant',
		synonyms: ['Romanian Cuisine', 'Romanian Food', 'Rumanian Cuisine', 'Rumanian Food'],
	},
	{
		id: 7315040,
		name: 'Russian Restaurant',
		synonyms: ['Russian Cuisine', 'Russian Food'],
	},
	{
		id: 7315143,
		name: 'Salad Bar',
		synonyms: ['Salad'],
	},
	{
		id: 7310006,
		name: 'Car Accessories',
		synonyms: ['Vehicle Accessories'],
	},
	{
		id: 7315042,
		name: 'Sandwich Restaurant',
		synonyms: [
			'Sandwich',
			'Sandwich Bar',
			'Sandwich Corner',
			'Sandwich Shop',
			'Sandwiches',
			'Sub Shop',
			'Submarine Sandwich',
			'Subs',
		],
	},
	{
		id: 9378005,
		name: 'Sauna, Solarium & Massage',
		synonyms: ['Day Spa', 'Spa', 'Wellness'],
	},
	{
		id: 9352010,
		name: 'Savings Institution',
		synonyms: ['Savings Bank'],
	},
	{
		id: 7315113,
		name: 'Savoy Restaurant',
		synonyms: ['Savoy Cuisine', 'Savoy Food'],
	},
	{
		id: 7315114,
		name: 'Scandinavian Restaurant',
		synonyms: ['Scandinavian Cuisine', 'Scandinavian Food'],
	},
	{
		id: 7372002,
		name: 'School',
		synonyms: ['Educational Institution'],
	},
	{
		id: 7315115,
		name: 'Scottish Restaurant',
		synonyms: ['Scottish Cuisine', 'Scottish Food'],
	},
	{
		id: 7315043,
		name: 'Seafood',
		synonyms: ['Seafood Restaurant'],
	},
	{
		id: 9362013,
		name: 'Seashore',
		synonyms: [],
	},
	{
		id: 7389004,
		name: 'Security Gate',
		synonyms: [],
	},
	{
		id: 9361078,
		name: 'Security Products',
		synonyms: ['Security Solutions'],
	},
	{
		id: 7372007,
		name: 'Senior High School',
		synonyms: [],
	},
	{
		id: 9352002,
		name: 'Service Company',
		synonyms: [],
	},
	{
		id: 7315053,
		name: 'Shandong Restaurant',
		synonyms: ['Lu Cuisine', 'Shandong Cuisine', 'Shandong Food'],
	},
	{
		id: 7315055,
		name: 'Shanghai Restaurant',
		synonyms: ['Hu Cuisine', 'Shanghai Cuisine', 'Shanghai Food'],
	},
	{
		id: 9361062,
		name: 'Shopping Service',
		synonyms: [],
	},
	{
		id: 7315056,
		name: 'Sichuan Restaurant',
		synonyms: [
			'Sichuan Cuisine',
			'Sichuan Food',
			'Szechuan Cuisine',
			'Szechuan Food',
			'Szechuan Restaurant',
			'Szechwan Cuisine',
		],
	},
	{
		id: 7315116,
		name: 'Sicilian Restaurant',
		synonyms: ['Sicilian Cuisine', 'Sicilian Food'],
	},
	{
		id: 9362026,
		name: 'Ski Resort',
		synonyms: ['Ski Retreat'],
	},
	{
		id: 7315117,
		name: 'Slavic Restaurant',
		synonyms: ['Slavic Cuisine', 'Slavic Food'],
	},
	{
		id: 7315080,
		name: 'Slovak Restaurant',
		synonyms: ['Slovak Cuisine', 'Slovak Food'],
	},
	{
		id: 7315139,
		name: 'Snacks Restaurant',
		synonyms: ['Chippie', "Fish 'n' Chips", 'Snack Bar', 'Snacks Centre'],
	},
	{
		id: 9378006,
		name: 'Snooker, Pool & Billiard',
		synonyms: [
			'Billiard',
			'Billiard Hall',
			'Pool',
			'Pool Hall',
			'Poolhall',
			'Poolroom',
			'Snooker',
			'Snooker Hall',
		],
	},
	{
		id: 7374004,
		name: 'Soccer Stadium',
		synonyms: ['Football Ground', 'Football Stadium', 'Soccer', 'Soccer Arena', 'Soccer Field'],
	},
	{
		id: 7315064,
		name: 'Soul Food',
		synonyms: ['Southern Cuisine', 'Southern Food', 'Southern Restaurant'],
	},
	{
		id: 7315140,
		name: 'Soup Restaurant',
		synonyms: ['Soup'],
	},
	{
		id: 7315044,
		name: 'Spanish Restaurant',
		synonyms: ['Spanish Cuisine', 'Spanish Food'],
	},
	{
		id: 7321003,
		name: 'Special Hospital',
		synonyms: ['Special Polyclinic'],
	},
	{
		id: 7372013,
		name: 'Special School',
		synonyms: [],
	},
	{
		id: 9373003,
		name: 'Specialist',
		synonyms: [],
	},
	{
		id: 9361061,
		name: 'Specialty Foods',
		synonyms: [],
	},
	{
		id: 7372011,
		name: 'Sport School',
		synonyms: ['Sports Academy'],
	},
	{
		id: 9361039,
		name: 'Sports Equipment & Clothing',
		synonyms: ['Sports Clothing', 'Sports Equipment'],
	},
	{
		id: 9361074,
		name: 'Stamp Shop',
		synonyms: ['Stamps'],
	},
	{
		id: 7389003,
		name: 'Station Access',
		synonyms: [],
	},
	{
		id: 7376013,
		name: 'Statue',
		synonyms: [],
	},
	{
		id: 7315045,
		name: 'Steak House',
		synonyms: ['Carvery', 'Steak Restaurant', 'Steakhouse'],
	},
	{
		id: 9160002,
		name: 'Stock Exchange',
		synonyms: [],
	},
	{
		id: 7315118,
		name: 'Sudanese Restaurant',
		synonyms: ['Sudanese Cuisine', 'Sudanese Food'],
	},
	{
		id: 7332005,
		name: 'Supermarkets & Hypermarkets',
		synonyms: ['Hypermarket', 'Hypermarkets', 'Supermarket', 'Supermarkets', 'Superstore'],
	},
	{
		id: 7315046,
		name: 'Surinamese Restaurant',
		synonyms: ['Surinamese Cuisine', 'Surinamese Food'],
	},
	{
		id: 7315148,
		name: 'Sushi Restaurant',
		synonyms: ['Sushi Bar', 'Sushi House'],
	},
	{
		id: 7315119,
		name: 'Swedish Restaurant',
		synonyms: ['Swedish Cuisine', 'Swedish Food'],
	},
	{
		id: 7315047,
		name: 'Swiss Restaurant',
		synonyms: ['Swiss Cuisine', 'Swiss Food'],
	},
	{
		id: 7339004,
		name: 'Synagog',
		synonyms: ['Synagogue'],
	},
	{
		id: 7315120,
		name: 'Syrian Restaurant',
		synonyms: ['Syrian Cuisine', 'Syrian Food'],
	},
	{
		id: 9361077,
		name: 'Tailor Shop',
		synonyms: ['Alterations', 'Tailor', 'Tailors'],
	},
	{
		id: 7315059,
		name: 'Taiwanese Restaurant',
		synonyms: ['Taiwanese Cuisine', 'Taiwanese Food'],
	},
	{
		id: 7315145,
		name: 'Takeout Food',
		synonyms: [
			'Carry-out',
			'Take Away',
			'Take Away Food',
			'Take Out',
			'Take-out',
			'Takeaway',
			'Takeaway Food',
			'Takeout',
			'Takeout Restaurant',
			'To Go',
		],
	},
	{
		id: 7315076,
		name: 'Tapas Restaurant',
		synonyms: ['Tapas', 'Tapas Bar'],
	},
	{
		id: 9352022,
		name: 'Tax Services',
		synonyms: [
			'Chartered Accountant',
			'Tax',
			'Tax Accountant',
			'Tax Agent',
			'Tax Broker',
			'Tax Consultants',
			'Tax Lawyer',
		],
	},
	{
		id: 9942003,
		name: 'Taxi Stand',
		synonyms: ['Cab', 'Cab Rank', 'Cab Stand', 'Taxi', 'Taxi Rank'],
	},
	{
		id: 9352026,
		name: 'Taxi, Limousine & Shuttle Service',
		synonyms: [],
	},
	{
		id: 9376005,
		name: 'Tea House',
		synonyms: ['Tea Room', 'Tea Stall'],
	},
	{
		id: 7372009,
		name: 'Technical School',
		synonyms: ['Polytechnic School', 'Technical College'],
	},
	{
		id: 9352020,
		name: 'Telecommunications',
		synonyms: ['Telecom', 'Telecoms'],
	},
	{
		id: 7339005,
		name: 'Temple',
		synonyms: ['Mandir'],
	},
	{
		id: 7315121,
		name: 'Teppanyaki Restaurant',
		synonyms: ['Teppanyaki Cuisine', 'Teppanyaki Food'],
	},
	{
		id: 7315048,
		name: 'Thai Restaurant',
		synonyms: ['Thai Cuisine', 'Thai Food'],
	},
	{
		id: 7318005,
		name: 'Theater',
		synonyms: ['Play House', 'Playhouse', 'Theatre'],
	},
	{
		id: 7320005,
		name: 'Thematic Sport Center',
		synonyms: ['Thematic Sport Centre'],
	},
	{
		id: 7315122,
		name: 'Tibetan Restaurant',
		synonyms: ['Tibetan Cuisine', 'Tibetan Food'],
	},
	{
		id: 9932005,
		name: 'Public Toilet',
		synonyms: [
			'Bathroom',
			'Public Bathroom',
			'Public Lavatories',
			'Public Rest Room',
			'Public Toilets',
			'Public W.C.',
			'Restroom',
			'Toilet',
			'Toilets',
			'WC',
			'Wash Room',
			'Washroom',
		],
	},
	{
		id: 7376009,
		name: 'Tower',
		synonyms: [],
	},
	{
		id: 7303005,
		name: 'Townhouse Complex',
		synonyms: [],
	},
	{
		id: 9361040,
		name: 'Toys & Games Shop',
		synonyms: [
			'Game Shop',
			'Games',
			'Games Shop',
			'Games Shops',
			'Gameshop',
			'Toy Shop',
			'Toy Store',
			'Toy Stores',
			'Toys',
			'Videogame Parlour',
			'Videogame Store',
		],
	},
	{
		id: 7301002,
		name: 'Traffic Control Department',
		synonyms: ['RTO', 'Traffic Management Department'],
	},
	{
		id: 9942004,
		name: 'Streetcar Stop',
		synonyms: ['Cable Car', 'Cable Car Stop', 'Streetcar', 'Tram', 'Tram Stop'],
	},
	{
		id: 9352024,
		name: 'Transport Company',
		synonyms: [],
	},
	{
		id: 9361041,
		name: 'Travel Agent',
		synonyms: ['Travel Agency', 'Travel Bureau'],
	},
	{
		id: 9910006,
		name: 'Truck Dealer',
		synonyms: ['Commercial Vehicle Dealer', 'Lorry Dealer', 'Truck Sales'],
	},
	{
		id: 7310009,
		name: 'Truck Repair and Service',
		synonyms: ['Lorry Repair', 'Lorry Service', 'Truck Repair', 'Truck Service'],
	},
	{
		id: 9155003,
		name: 'Truck Wash',
		synonyms: [],
	},
	{
		id: 7315123,
		name: 'Tunisian Restaurant',
		synonyms: ['Tunisian Cuisine', 'Tunisian Food'],
	},
	{
		id: 7376008,
		name: 'Tunnel',
		synonyms: [],
	},
	{
		id: 7315049,
		name: 'Turkish Restaurant',
		synonyms: ['Turkish Cuisine', 'Turkish Food'],
	},
	{
		id: 7310007,
		name: 'Tire Service',
		synonyms: [
			'Tire Center',
			'Tire Centre',
			'Tire Retail',
			'Tire Shop',
			'Tyre Centre',
			'Tyre Retail',
			'Tyre Service',
			'Tyre Shop',
		],
	},
	{
		id: 7315124,
		name: 'Uruguayan Restaurant',
		synonyms: ['Uruguayan Cuisine', 'Uruguayan Food'],
	},
	{
		id: 8099006,
		name: 'Valley',
		synonyms: [],
	},
	{
		id: 9910007,
		name: 'Van Dealer',
		synonyms: ['Van Sales'],
	},
	{
		id: 9361081,
		name: 'Variety Store',
		synonyms: [],
	},
	{
		id: 7315050,
		name: 'Vegetarian Restaurant',
		synonyms: ['Vegetarian Cuisine', 'Vegetarian Food'],
	},
	{
		id: 7315125,
		name: 'Venezuelan Restaurant',
		synonyms: ['Venezuelan Cuisine', 'Venezuelan Food'],
	},
	{
		id: 7315051,
		name: 'Vietnamese Restaurant',
		synonyms: ['Vietnamese Cuisine', 'Vietnamese Food'],
	},
	{
		id: 7304003,
		name: 'Villa Rental',
		synonyms: [],
	},
	{
		id: 7372008,
		name: 'Vocational School',
		synonyms: ['ITI', 'Trade School', 'Vocational Education', 'Vocational Training'],
	},
	{
		id: 7376014,
		name: 'Water Hole',
		synonyms: [],
	},
	{
		id: 9352046,
		name: 'Wedding Services',
		synonyms: ['Wedding Planners', 'Wedding Planning'],
	},
	{
		id: 7359003,
		name: 'Weigh Scales',
		synonyms: [
			'Compliance Station',
			'HVSS',
			'Heavy Vehicle Safety Station',
			'Heavy Vehicle Safety Stations',
			'Weigh Bridge',
			'Weigh Scale',
		],
	},
	{
		id: 8099010,
		name: 'Well',
		synonyms: [],
	},
	{
		id: 7315126,
		name: 'Welsh Restaurant',
		synonyms: ['Welsh Cuisine', 'Welsh Food'],
	},
	{
		id: 7315060,
		name: 'Western Restaurant',
		synonyms: [
			'Continental Cuisine',
			'Continental Food',
			'Continental Restaurant',
			'European Cuisine',
			'European Food',
			'European Restaurant',
			'Western Cuisine',
			'Western Food',
		],
	},
	{
		id: 9361066,
		name: 'Wholesale Club',
		synonyms: ['Warehouse Club', 'Wholesale Shop'],
	},
	{
		id: 9362014,
		name: 'Wilderness Area',
		synonyms: ['SSSI'],
	},
	{
		id: 9927005,
		name: 'Wildlife Park',
		synonyms: [
			'Safari Park',
			'Wildlife',
			'Wildlife Conservation',
			'Wildlife Refuge',
			'Wildlife Sanctuary',
		],
	},
	{
		id: 9379007,
		name: 'Wine Bar',
		synonyms: ['Wine'],
	},
	{
		id: 7347003,
		name: 'Yacht Basin',
		synonyms: ['Yacht Club'],
	},
	{
		id: 7315149,
		name: 'Yogurt/Juice Bar',
		synonyms: ['Juice Bar', 'Yoghurt Bar', 'Yogurt Bar'],
	},
	{
		id: 9927003,
		name: 'Zoo',
		synonyms: ['Zoological Collection', 'Zoological Garden'],
	},
	{
		id: 9352015,
		name: 'Electronics Company',
		synonyms: ['Electronics Supplier'],
	},
	{
		id: 7302005,
		name: 'Horse Riding Trail',
		synonyms: ['Horse Riding Path'],
	},
	{
		id: 7321002,
		name: 'Hospital',
		synonyms: [
			'Clinic',
			'Hospice',
			'Hospital/Polyclinic',
			'Infirmary',
			'Medical Centre',
			'Polyclinic',
			'Primary Care Centre',
		],
	},
	{
		id: 7376004,
		name: 'Natural Tourist Attraction',
		synonyms: ['Natural Attraction'],
	},
	{
		id: 7369002,
		name: 'Open Car Parking Area',
		synonyms: [],
	},
	{
		id: 9360,
		name: 'Ice Skating Rink',
		synonyms: ['Ice Rink', 'Ice Skating', 'Skating Rink'],
	},
	{
		id: 9369,
		name: 'Tennis Court',
		synonyms: ['Tennis'],
	},
	{
		id: 9911,
		name: 'Golf Course',
		synonyms: [
			'Driving Range',
			'Golf',
			'Golf Club',
			'Golf Game',
			'Golf Links',
			'Golf Round',
			'Links',
			'Links Course',
		],
	},
	{
		id: 9371,
		name: 'Water Sport',
		synonyms: ['Water Sports'],
	},
	{
		id: 7338,
		name: 'Swimming Pool',
		synonyms: [
			'Aquatic Center',
			'Baths',
			'Community Pool',
			'Pool',
			'Public Pool',
			'Swimming Baths',
			'Water Park',
		],
	},
	{
		id: 9359,
		name: 'Restaurant Area',
		synonyms: ['Dining Area', 'Food Court'],
	},
	{
		id: 9374,
		name: 'Dentist',
		synonyms: [
			'Dental Practitioner',
			'Dental Surgery',
			"Dentist's Office",
			'Denture Repair',
			'Dentures',
			'Orthodontist',
			'Teeth',
			'Tooth Doctor',
		],
	},
	{
		id: 9375,
		name: 'Veterinarian',
		synonyms: [
			'Animal Clinic',
			'Animal Doctor',
			'Animal Hospital',
			'Vet',
			'Vet Clinic',
			'Veterinary Clinic',
			'Veterinary Doctor',
			'Veterinary Surgeon',
		],
	},
	{
		id: 7326,
		name: 'Pharmacy',
		synonyms: ['Medication', 'Medicine', 'Pharmacist'],
	},
	{
		id: 9956,
		name: 'EmergencyRoom',
		synonyms: ['Emergency Room'],
	},
	{
		id: 7327,
		name: 'Department Store',
		synonyms: ['General Store'],
	},
	{
		id: 7373,
		name: 'Shopping Center',
		synonyms: [
			'Mall',
			'Precinct',
			'Shopping Arcade',
			'Shopping Centre',
			'Shopping Complex',
			'Shopping Mall',
			'Shopping Precinct',
		],
	},
	{
		id: 7392,
		name: 'Fire Station',
		synonyms: [
			'Fire Brigade',
			'Fire Department',
			'Fire Hall',
			'Fire Service',
			'Fire Station/Brigade',
			'Firehouse',
			'Firemen',
		],
	},
	{
		id: 9152,
		name: 'Non Governmental Organization',
		synonyms: ['NGO', 'Non Governmental Organisation', 'Non-Governmental Organization'],
	},
	{
		id: 9154,
		name: 'Prison/Correctional Facility',
		synonyms: [
			'Correctional Department',
			'Correctional Facility',
			'Jail',
			'Prison',
			'Remand Home',
		],
	},
	{
		id: 7365,
		name: 'Embassy',
		synonyms: [
			'Commission',
			'Consul',
			'Consulate',
			'Delegation',
			'Diplomat',
			'Diplomatic Building',
			'Diplomatic Mission',
			'High Commission',
			'Mission',
			'Permanent Mission',
		],
	},
	{
		id: 9913,
		name: 'Library',
		synonyms: ['Book Collection', 'Book Depository', 'Books', 'Public Library'],
	},
	{
		id: 9151,
		name: 'Transport Authority/Vehicle Registration Office',
		synonyms: [
			'DMV',
			'Department of Motor Vehicles',
			'MOT',
			'Ministry of Transport',
			'RTO',
			'Transport Authority',
			'Transport Authority/Vehicle Registration',
			'Vehicle Registration',
			'Vehicle Registration Office',
			'WOF',
			'Warrant of Fitness',
		],
	},
	{
		id: 9153,
		name: 'Welfare Organization',
		synonyms: ['Trust', 'Welfare', 'Welfare Organisation'],
	},
	{
		id: 9389,
		name: 'Native Reservation',
		synonyms: [],
	},
	{
		id: 9363,
		name: 'Courthouse',
		synonyms: [
			'Court House',
			'Court of Justice',
			'Court of Law',
			'Courtroom',
			'Crown Court',
			'High Court',
			'Judiciary',
			'Law Court',
			'Law Courts',
			'Lawcourt',
			'Lawcourts',
			'Magistrate Court',
			'Small Claims Court',
			'Tribunal',
		],
	},
	{
		id: 7322,
		name: 'Police Station',
		synonyms: ['Cops', 'Police', 'Police Department', 'Police Headquarters', 'Station House'],
	},
	{
		id: 9150,
		name: 'Primary Resource/Utility',
		synonyms: [
			'Primary Resource',
			'Primary Resources',
			'Primary Utilities',
			'Primary Utility',
			'Utilities',
			'Utility',
		],
	},
	{
		id: 7367,
		name: 'Government Office',
		synonyms: [
			'Federal Building',
			'Federal Office',
			'Government Agency',
			'Government Building',
			'Municipality',
		],
	},
	{
		id: 9388,
		name: 'Military Installation',
		synonyms: ['Barracks', 'Cantonment Area', 'Military Base'],
	},
	{
		id: 9930,
		name: 'Rent-a-Car-Parking',
		synonyms: [
			'Hire Car Parking',
			'Rent-a-Car Parking',
			'Rental Car Parking',
			'Rental Parking',
			'Rental Parking Garage',
		],
	},
	{
		id: 7317,
		name: 'Museum',
		synonyms: ['Art Gallery'],
	},
	{
		id: 9383,
		name: 'Industrial Building',
		synonyms: [],
	},
	{
		id: 7313,
		name: 'Parking Garage',
		synonyms: [
			'Car Park',
			'Indoor Parking',
			'Parking',
			'Parking Lot',
			'Parking Place',
			'Parking Ramp',
			'Parking Structure',
			'Secure Parking',
		],
	},
	{
		id: 7316,
		name: 'Tourist Information Office',
		synonyms: [
			'I-site',
			'Information Center',
			'Information Centre',
			'Information Office',
			'Tourist Center',
			'Tourist Centre',
			'Tourist Information',
			'Tourist Information Center',
			'Tourist Information Centre',
			'Tourist Office',
			'Visitor Center',
			'Visitor Centre',
			'Visitor Information Center',
			'Visitor Information Centre',
		],
	},
	{
		id: 9158,
		name: 'Media Facility',
		synonyms: [
			'Broadcaster',
			'Broadcasting House',
			'Media Center',
			'Media Centre',
			'Media House',
			'Media Studio',
		],
	},
	{
		id: 7349,
		name: 'Winery',
		synonyms: [
			'Vinery',
			'Vineyard',
			'Vintner',
			'Wine',
			'Wine Estate',
			'Wine Maker',
			'Winemaker',
		],
	},
	{
		id: 7391,
		name: 'Emergency Medical Service',
		synonyms: [
			'A & E',
			'A&E',
			'Accident & Emergency Unit',
			'Accident and Emergency',
			'Ambulance Service',
			'Casualty',
			'Emergency Call Station',
			'Emergency Department',
			'Emergency Ward',
			'First Aid',
			'First Aid Post',
			'First Aid Station',
			'Medical Centre',
			'Medical Service',
			'Minor Injuries Unit',
			'Trauma Center',
			'Urgent Care',
		],
	},
	{
		id: 7341,
		name: 'Casino',
		synonyms: ['Betting', 'Gambling', 'Gaming Parlour'],
	},
	{
		id: 9156,
		name: 'Manufacturing Facility',
		synonyms: ['Factory', 'Manufacturing Plant', 'Production Plant'],
	},
	{
		id: 9382,
		name: 'Commercial Building',
		synonyms: [],
	},
	{
		id: 7319,
		name: 'Cultural Center',
		synonyms: [
			'Community Arts Center',
			'Cultural Centre',
			'Ethnic Center',
			'Ethnic Centre',
			'Ethnic Cultural Center',
			'Ethnic Heritage Center',
		],
	},
	{
		id: 9377,
		name: 'Exhibition & Convention Center',
		synonyms: [
			'Assembly Center',
			'Conference Center',
			'Conference Hall',
			'Convention Center',
			'Convention Centre',
			'Exhibition & Convention Centre',
			'Exhibition Center',
			'Exhibition Centre',
			'Meeting Center',
			'Meeting Centre',
		],
	},
	{
		id: 7312,
		name: 'Rent-a-Car Facility',
		synonyms: [
			'Car Hire',
			'Car Rental',
			'Car Rental Facility',
			'Car Rental Services',
			'Rent a Car',
			'Rent-a-Car',
			'Self-Drive',
			'U-Drive',
			'Ute Rental',
			'You-Drive',
		],
	},
	{
		id: 7358,
		name: 'Truck Stop',
		synonyms: [
			'Bus & Truck Park',
			'Coach & Lorry Parking',
			'Coach & Truck Parking',
			'Coach and Lorry Parking',
			'Dhaba',
			'Transport Café',
			'Truck Service',
		],
	},
	{
		id: 7305,
		name: 'Adventure Sports Facility',
		synonyms: ['Adventure Sports', 'Adventure Sports Venue', 'Outdoor Centre'],
	},
	{
		id: 7395,
		name: 'Rest Area',
		synonyms: [
			'Break Area',
			'Food Plaza',
			'Highway Services',
			'Lay-by',
			'Layby',
			'Rest Stop',
			'Service Area',
			'Services',
		],
	},
	{
		id: 9157,
		name: 'Research Facility',
		synonyms: ['Research Center', 'Research Centre', 'Research Institute'],
	},
	{
		id: 7388,
		name: 'Courier Drop Box',
		synonyms: ['Drop Box'],
	},
	{
		id: 7311,
		name: 'Gas Station',
		synonyms: [
			'Diesel Station',
			'Expressway Services',
			'Filling Station',
			'Fuel Station',
			'Fuel Stop',
			'Gasoline Station',
			'Motorway Services',
			'Oil Supplier',
			'PULP',
			'Petrol Pump',
			'Petrol Station',
			'Service Station',
			'Servo',
		],
	},
	{
		id: 7368,
		name: 'Motoring Organization Office',
		synonyms: ['AA', 'Automobile Association', 'Motoring Association'],
	},
	{
		id: 7397,
		name: 'ATM',
		synonyms: [
			'ATM Machine',
			'Automated Teller Machine',
			'Automatic Teller',
			'Automatic Teller Machine',
			'Bank Machine',
			'Cash Dispenser',
			'Cash Machine',
			'Cash Point',
			'Cashpoint',
			'Money Machine',
			'Teller',
		],
	},
	{
		id: 7363,
		name: 'Community Center',
		synonyms: ['Community Centre', 'Village Hall', 'Youth Centre'],
	},
	{
		id: 9357,
		name: 'Beach',
		synonyms: [
			'Coast',
			'Margin',
			'Rim',
			'Sand',
			'Sand Dune',
			'Sea',
			'Shore',
			'Strand',
			'Sunbathing',
			'Swimming',
		],
	},
	{
		id: 9159,
		name: 'Port/Warehouse Facility',
		synonyms: [
			'Harbor Facilities',
			'Harbour Facilities',
			'Port Facility',
			'Port Trust',
			'Storage',
			'Storage Facility',
			'Warehouse',
			'Warehouse Facility',
		],
	},
	{
		id: 7309,
		name: 'Electric Vehicle Charging Station',
		synonyms: [
			'Battery Switching Station',
			'Charge Station',
			'Charging Station',
			'EV Charging Station',
			'EV station',
			'Electric Car Charge Point',
			'Electric Car Charging Station',
			'Electric Vehicle Charge Point',
			'Electric Vehicle Station',
		],
	},
	{
		id: 7337,
		name: 'Scenic/Panoramic View',
		synonyms: [
			'Beauty Spot',
			'Lookout',
			'Panorama',
			'Panoramic View',
			'Scenery',
			'Scenic',
			'Scenic View',
			'Viewpoint',
			'Vista',
		],
	},
	{
		id: 9900,
		name: 'Entertainment',
		synonyms: [],
	},
	{
		id: 7378,
		name: 'Business Park',
		synonyms: ['Enterprise Park', 'Enterprise Zone', 'Office Park'],
	},
	{
		id: 7328,
		name: 'Bank',
		synonyms: ['Credit Union'],
	},
	{
		id: 7308,
		name: 'Helipad',
		synonyms: ['Helicopter', 'Helicopter Landing', 'Helicopter Landing Pad', 'Heliport'],
	},
	{
		id: 9955,
		name: 'Checkpoint',
		synonyms: [],
	},
	{
		id: 7366,
		name: 'Frontier Crossing',
		synonyms: [
			'Border',
			'Border Control',
			'Border Crossing',
			'Border Line',
			'Border Security',
			'Borderline',
			'Checkpost',
			'Customs',
			'Customs Office',
			'Frontier',
			'Integrated Check Post',
			'Landing Custom Station',
		],
	},
	{
		id: 9935,
		name: 'Mountain Pass',
		synonyms: ['Mountain Road'],
	},
	{
		id: 7375,
		name: 'Toll Gate',
		synonyms: ['Toll Bar', 'Toll Booth', 'Toll Collection Gate', 'Toll Plaza', 'Toll Station'],
	},
	{
		id: 7352,
		name: 'Ferry Terminal',
		synonyms: [
			'Ferries',
			'Ferry',
			'Ferry Crossing',
			'Ferry Dock',
			'Ferry Station',
			'Ferry Wharf',
		],
	},
];
